ingress:
  # API Subdomain for Backend - route ALL paths to internal API Gateway
  - hostname: api.radiox.cloud
    service: http://api-gateway:8000
    
  # Catch-all rule (required) - must be last
  - service: http_status:404 